spring:
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3307}/${DATABASE_NAME:local_ratta_db}
   #?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
   username: ${DATABASE_USER:local_ratta_user}
   password: ${DATABASE_USER:local_ratta_password}

 jpa:
   database-platform: org.hibernate.dialect.MySQL8Dialect
   hibernate:
     ddl-auto: update
   properties:
     hibernate:
       format_sql: true
       show_sql: true
   open-in-view: false

logging:
 level:
   root: info
   com.forrrest: debug
   org.hibernate.SQL: debug
   org.hibernate.type: trace

server:
  port: ${SAMPLE_PORT:8080}

security:
  token:
    app-management-server-paths: ${app_management_server_paths:http://localhost:8082}

    #http:://222.233.6.72:17172
    #http://localhost:8082