spring:
  profiles:
    active: local

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

token:
  secret: ${TOKEN_SECRET:YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXphYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5eg==}
  validity:
    USER_ACCESS: 3600000        # 1시간
    USER_REFRESH: 604800000     # 7일
    PROFILE_ACCESS: 3600000     # 1시간
    PROFILE_REFRESH: 604800000  # 7일
    NONCE: 300000              # 5분
# 필터를 거치고 싶은 경로만 추가, 추가 안한 나머지 경로 필터 검사 x 그냥 통과
security:
  token:
    user-paths: #/users, /profiles
    profile-paths: /profile-tokens/test
    nonce-paths: #/nonce-tokens
    external-nonce-paths: /nonce-tokens

logging:
  level:
    root: info
    com.forrrest: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: ${SAMPLE_PORT:8080}

forrrest:
  app-management-service:
    host: ${APP_MANAGEMENT_SERVICE_HOST:localhost}
    port: ${APP_MANAGEMENT_SERVICE_PORT:8081}